import turtle
a=turtle.Turtle()
a.color("pink")
a.penup()
a.goto(0,100)
b=turtle.Turtle()
b.color("blue")
b.penup()
b.goto(0,-300)
a.pendown()
a.circle(50)
b.pendown()
b.write("1 done 4 to go")
a.right(60)
a.circle(50)
b.write("2 done 3 to go")
a.right(60)
a.circle(50)
b.write("3 done 2 to go")
a.right(60)
a.circle(50)
b.write("4 done 1 to go")
a.right(60)
a.circle(50)
b.write("all 5 done none left")

